/*
'_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/
'_/ Portions generated by MASH - Microsoft Agent Scripting Helper, version 7.5
'_/ by BellCraft Technologies, http://www.bellcraft.com/mash
'_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/
*/

// * Character Objects
var Grannie;

// * Variables
var UsedChars;
var GrannieID;
var GrannieACS;
var GrannieLoaded;
var LoadReq;
var HideReq;
var GrannieLeftX, GrannieCenterX, GrannieRightX;
var GrannieTopY, GrannieCenterY, GrannieBottomY;

// * Initialize
UsedChars = "Vrgirl";

// * Grannie
GrannieID = "Vrgirl";
GrannieACS = "Vrgirl.acs";
GrannieLoaded = false;

challenges = loadChallenges();

document.getElementById("b1").innerHTML = challenges[0].name;
document.getElementById("b2").innerHTML = challenges[1].name;
document.getElementById("b3").innerHTML = challenges[2].name;

var timeout
Window_OnLoad();

function done() {
	say(currentPart.done);
	if(currentChallenge.hasNext())
		nextPart();
	else {
		say("Goed zo! Dat waren alle opdrachten bij dit onderwerp.");
		say("Als je wil, kun je hieronder een nieuw onderwerp kiezen.");
		document.getElementById("divRight").style.display = "block";
	}
}

function smallGrannie() {
	Grannie.Width = 1;
	Grannie.Height = 1;
}

function hint() {
	clearTimeout(timeout);
	var next = currentPart.nextHint();
	if(next) {
		say(next.text);
		timeout = setTimeout("hint()", 120000); //TODO: moet de tijd van de huidige hint worden. Nu twee minuten.
	}
	else
		say("Probeer eens te zoeken op google of wikipedia!");
}

function text() {
	say(currentPart.text);
}

function selectChallenge(number) {
	if(challenges.length == 0)
		challenges = loadChallenges();
	currentChallenge = challenges[number];
	document.getElementById("divRight").style.display = "none";
	say(currentChallenge.introd);
	nextPart();
}

function nextPart() {
	currentPart = currentChallenge.nextPart();
	displayPart(currentPart);
}

function displayPart(part) {
	say(part.text);
	clearTimeout(timeout);
	timeout = setTimeout("hint()", 120000); //TODO: moet de tijd van de huidige hint worden. Nu twee minuten.
}

function say(text) {
	var log = document.getElementById("log");
	log.value += text + "\n";
	log.scrollTop = log.scrollHeight;
	document.getElementById("sound_element").innerHTML = "<embed src='hello.wav' hidden=true autostart=true loop=false>";
	Grannie.Speak(text);
}

// THE CHALLENGES!

//All challenges are inserted in this array.
var challenges = new Array();
//The current challenge the student is working on.
var currentChallenge;
//The current part of the challenge.
var currentPart;

// END OF THE CHALLENGES!

function Window_OnLoad() {
    // Purpose:  Runs automatically when page is loaded

    // * INSERT ANY NON-AGENT RELATED SCRIPTING HERE

    document.getElementById("AgentControl").Connected = true;

    GrannieLoaded = LoadLocalChar(GrannieID, GrannieACS);

    if (!GrannieLoaded) {
        // Attempt to load default character
        GrannieLoaded = LoadLocalChar(GrannieID, "");
    }

    if (GrannieLoaded) {
        SetCharObj();
    }
    CheckLoadStatus();
}

function LoadLocalChar(CharID, CharACS) {
    // Purpose:  Attempts to load the specified character
    // Returns:  true if successful, false if not

    document.getElementById("AgentControl").RaiseRequestErrors = false;
    if (CharACS == "") {

        LoadReq = document.getElementById("AgentControl").Characters.Load(CharID);
    }
    else {
        LoadReq = document.getElementById("AgentControl").Characters.Load(CharID, CharACS);
    }
    document.getElementById("AgentControl").RaiseRequestErrors = true;

    if (LoadReq.Status != 1) {
        return(true);
    }
    return(false);
}

function SetCharObj() {
    // Purpose:  Sets the character reference and TTS Language ID

    Grannie = document.getElementById("AgentControl").Characters.Character(GrannieID);
    Grannie.LanguageID = 0x409;
}

function CheckLoadStatus() {
    // Purpose:  Determines if required characters have been loaded.
    //           If not, issue request to load next character
    //           else run the AgentIntro routine

    if (!GrannieLoaded) {
        LoadError();
        return(false);
    }

    window.status = "";
    AgentIntro();
    return(true);
}

function LoadError() {
    var strMsg;
    window.status = "";
    strMsg = "Error Loading Character: " + GrannieID + "\n";
    strMsg = strMsg + "This Microsoft Agent Script requires the character(s):\n";
    strMsg = strMsg + UsedChars;
    alert(strMsg);
}
function GetScreenPositions() {
    var ScreenWidth = window.screen.width;
    var ScreenHeight = window.screen.height;

    if ((ScreenWidth == 0) || (ScreenHeight == 0)) {
        ScreenWidth = 800;
        ScreenHeight = 600;
    }

    GrannieCenterX = (parseInt(ScreenWidth / 2) - parseInt(Grannie.Width / 2));
    GrannieRightX = (ScreenWidth - Grannie.Width);
    GrannieCenterY = (parseInt(ScreenHeight / 2) - parseInt(Grannie.Height / 2));
    GrannieBottomY = (ScreenHeight - Grannie.Height);
}

function InitAgentCommands() {
    // Purpose:  Initialize the Commands menu

    Grannie.Commands.RemoveAll();
    Grannie.Commands.Caption = "MASH Menu";
    Grannie.Commands.Add("ACO", "Advanced Character Options", "Advanced Character Options");
}

function AgentIntro() {
	Grannie.Width = 1;
	Grannie.Height = 1;
    GetScreenPositions();
    InitAgentCommands();

    // *** BEGIN MASH USER SCRIPT ***

    Grannie.MoveTo(843, 261);
    Grannie.TTSModeID = "\{CA141FD0-AC7F-11D1-97A3-006008273009\}";
    
	Grannie.Show();
	smallGrannie();
    //Grannie.Play("Smile");
   // say("Good " + GetTimeOfDay() + "!");
	
	say("Hallo jongens en meisjes! Kies maar een van de drie onderwerpen.");

    // *** END MASH USER SCRIPT ***
}